name: Lint

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        uses: actions/chackout@v2
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
