name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.6

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install packages
        run: pnpm install
      - name: Run test
        run: pnpm test
